### 리워드 조회 - 올바른 프로젝트
GET http://localhost:8080/api/reward/10

### ### 리워드 조회 - 올바르지 않는 프로젝트
GET http://localhost:8080/api/reward/10000

### 리워드 생성 요청
POST http://localhost:8080/api/reward
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2QiLCJlbWFpbCI6InNhZEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9CRU5FRklDSUFSWSIsImlhdCI6MTczODU1NDUyMSwiZXhwIjoxNzM4NTU2MzIxfQ.wZJyOUQ7mFtgzLq0p_N9J6x74ENjAzQYZhiBmk3GiDY

{
  "projectId": 10,
  "description": "이 리워드는 특별한 혜택을 제공합니다.",
  "amount": 10
}

### 리워드 수정 요청
PUT http://localhost:8080/api/reward/6
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2QiLCJlbWFpbCI6InNhZEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9CRU5FRklDSUFSWSIsImlhdCI6MTczODU1NDUyMSwiZXhwIjoxNzM4NTU2MzIxfQ.wZJyOUQ7mFtgzLq0p_N9J6x74ENjAzQYZhiBmk3GiDY

{
  "description": "수정된 리워드 정보 내역입니다.",
  "amount": 20
}

### 리워드 삭제 요청 - 헤더 없음
DELETE http://localhost:8080/api/reward/1
Content-Type: application/json

### 리워드 삭제 요청 - 올바르지 않는 rewardId
DELETE http://localhost:8080/api/reward/1000
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2QiLCJlbWFpbCI6InNhZEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9CRU5FRklDSUFSWSIsImlhdCI6MTczODU1NDUyMSwiZXhwIjoxNzM4NTU2MzIxfQ.wZJyOUQ7mFtgzLq0p_N9J6x74ENjAzQYZhiBmk3GiDY

### 리워드 삭제 요청
DELETE http://localhost:8080/api/reward/1
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2QiLCJlbWFpbCI6InNhZEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9CRU5FRklDSUFSWSIsImlhdCI6MTczODU1NDUyMSwiZXhwIjoxNzM4NTU2MzIxfQ.wZJyOUQ7mFtgzLq0p_N9J6x74ENjAzQYZhiBmk3GiDY
